// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator
// Simplified manually

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Grimoire_Gen
{
    public class Rect
    {
        [JsonProperty("x")]
        public int X { get; set; }

        [JsonProperty("y")]
        public int Y { get; set; }

        [JsonProperty("height")]
        public int Height { get; set; }

        [JsonProperty("width")]
        public int Width { get; set; }
    }

    public class Image
    {
        [JsonProperty("rect")]
        public Rect Rect { get; set; }

        [JsonProperty("sheetPath")]
        public string SheetPath { get; set; }

        [JsonProperty("sheetSize")]
        public Rect SheetSize { get; set; }
    }

    public class XResolution
    {
        [JsonProperty("image")]
        public Image Image { get; set; }

        [JsonProperty("smallImage")]
        public Image SmallImage { get; set; }
    }

    public class RankCollection
    {
        [JsonProperty("rank")]
        public int Rank { get; set; }

        [JsonProperty("threshold")]
        public int Threshold { get; set; }

        [JsonProperty("unlockFlagHash")]
        public int UnlockFlagHash { get; set; }

        [JsonProperty("points")]
        public int Points { get; set; }
    }

    public class StatisticCollection
    {
        [JsonProperty("statNumber")]
        public int StatNumber { get; set; }

        [JsonProperty("cardId")]
        public int CardId { get; set; }

        [JsonProperty("statName")]
        public string StatName { get; set; }

        [JsonProperty("accumulatorHash")]
        public int AccumulatorHash { get; set; }

        [JsonProperty("rankCollection")]
        public RankCollection[] RankCollection { get; set; }
    }

    public class BonusRank
    {
        [JsonProperty("statId")]
        public int StatId { get; set; }

        [JsonProperty("rank")]
        public int Rank { get; set; }
    }

    public class GrimoireCard
    {
        [JsonProperty("cardId")]
        public int CardId { get; set; }

        [JsonProperty("cardName")]
        public string CardName { get; set; }

        [JsonProperty("cardIntro")]
        public string CardIntro { get; set; }

        [JsonProperty("cardDescription")]
        public string CardDescription { get; set; }

        [JsonProperty("unlockHowToText")]
        public string UnlockHowToText { get; set; }

        [JsonProperty("rarity")]
        public int Rarity { get; set; }

        [JsonProperty("unlockFlagHash")]
        public int UnlockFlagHash { get; set; }

        [JsonProperty("points")]
        public int Points { get; set; }

        [JsonProperty("normalResolution")]
        public XResolution NormalResolution { get; set; }

        [JsonProperty("highResolution")]
        public XResolution HighResolution { get; set; }

        [JsonProperty("statisticCollection")]
        public StatisticCollection[] StatisticCollection { get; set; }

        [JsonProperty("cardLabel")]
        public string CardLabel { get; set; }

        [JsonProperty("cardIntroAttribution")]
        public string CardIntroAttribution { get; set; }

        [JsonProperty("bonusName")]
        public string BonusName { get; set; }

        [JsonProperty("bonusDescription")]
        public string BonusDescription { get; set; }

        [JsonProperty("bonusRank")]
        public BonusRank BonusRank { get; set; }
    }

    public class CardBrief
    {
        [JsonProperty("cardId")]
        public int CardId { get; set; }

        [JsonProperty("points")]
        public int Points { get; set; }

        [JsonProperty("totalPoints")]
        public int TotalPoints { get; set; }
    }

    public class PageCollection
    {
        [JsonProperty("pageId")]
        public string PageId { get; set; }

        [JsonProperty("pageName")]
        public string PageName { get; set; }

        [JsonProperty("normalResolution")]
        public XResolution NormalResolution { get; set; }

        [JsonProperty("highResolution")]
        public XResolution HighResolution { get; set; }

        [JsonProperty("cardCollection")]
        public GrimoireCard[] GrimoireCard { get; set; }

        [JsonProperty("cardBriefs")]
        public CardBrief[] CardBriefs { get; set; }
    }

    public class ThemeCollection
    {
        [JsonProperty("themeId")]
        public string ThemeId { get; set; }

        [JsonProperty("themeName")]
        public string ThemeName { get; set; }

        [JsonProperty("normalResolution")]
        public XResolution NormalResolution { get; set; }

        [JsonProperty("highResolution")]
        public XResolution HighResolution { get; set; }

        [JsonProperty("pageCollection")]
        public PageCollection[] PageCollection { get; set; }

        [JsonProperty("themeDescription")]
        public string ThemeDescription { get; set; }
    }

    public class Response
    {
        [JsonProperty("themeCollection")]
        public ThemeCollection[] ThemeCollection { get; set; }
    }

    public class MessageData
    {
    }

    public class GrimoireDefinitions
    {
        [JsonProperty("Response")]
        public Response Response { get; set; }

        [JsonProperty("ErrorCode")]
        public int ErrorCode { get; set; }

        [JsonProperty("ThrottleSeconds")]
        public int ThrottleSeconds { get; set; }

        [JsonProperty("ErrorStatus")]
        public string ErrorStatus { get; set; }

        [JsonProperty("Message")]
        public string Message { get; set; }

        [JsonProperty("MessageData")]
        public MessageData MessageData { get; set; }
    }

}
